### ISSUE TITLE
[FR] Changing TFT_driver to have full color spectrum on Elegoo Neptune 2/2S/D

### ISSUE THREAD

**Issue by escapppe** [just-trey/Marlin#13]
### Is your feature request related to a problem? Please describe.

Changing the Driver in Marlin\src\inc\Conditionals_LCD.h 
on Line: 1265 from ILI9488 to ILI9341 adds full color options (white is white not light green)

#elif ANY(MKS_ROBIN_TFT35, TFT_TRONXY_X5SA, ANYCUBIC_TFT35)                   // ILI9488
  #define TFT_DRIVER ILI9341 // this here
  #define TFT_DEFAULT_ORIENTATION (TFT_EXCHANGE_XY | TFT_INVERT_X | TFT_INVERT_Y)
  #define TFT_RES_480x320
  #define TFT_INTERFACE_FSMC

**Comment by just-trey** [comment]
Holy cow I just saw this. I'll look at it ASAP!

**Comment by just-trey** [comment]
@escapppe testing a release hopefully will include this tomorrow

**Comment by Babble69** [comment]
Hey, just-trey I am having a problem with my install.  I'm a total noob to the firmware side of things, but know everything about the printer side, can you please contact me back and I can explain what is going on? Thanks!!

**Comment by just-trey** [comment]
@Babble69  I need a way to contact you. Email? Discord? Something else?

**Comment by just-trey** [comment]
https://github.com/just-trey/Marlin/releases/tag/2.0.9.3-N2-rc3 resolved this. @escapppe  I was able to do this in  [configuration.h](https://github.com/just-trey/Marlin/blob/933c0fa99dd5d0e13d4c62106cae115a9b2f4f3a/config/Elegoo/Neptune-2/Configuration.h#L2839-L2853) rather than have to change the file you pointed to.
